### PR TITLE
Signup fixes

### LINKED ISSUE #32: sign up does not work
On the sign up page, if I fill in the data and click "sign up", nothing happens.

### PR DESCRIPTION
**Pull request by pramodkumarbontha**
#32 , #10 Signup and login fixes.

### CODE REVIEW

File: frontend/lqclient/src/components/Authentication/SignUp.jsx [hunk 1]
```diff
@@ -9,76 +9,149 @@ import Grid from "@material-ui/core/Grid";
...
+    } else if (password1 && password1.length <= 8) {
+      this.setState({
+        openSnackBar: true,
+        errorMessage: "Minimum password length is 8 characters"
+      });
+      return false;
+    } else if (password1 && password2 && password1 !== password2) {
+      this.setState({
+        openSnackBar: true,
+        errorMessage: "Passwords Doesnot match"
```
Comment (tillmo) [inline frontend/lqclient/src/components/Authentication/SignUp.jsx:124]: correct English is "passwords do not match". This brings me to another point: I think that there are standard libraries for such things. Can't you just re-use them?

File: backend/lqserver/lqserver/settings.py [hunk 2]
```diff
@@ -105,12 +105,6 @@
     {
         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
     },
-    {
-        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
-    },
-    {
-        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
-    },
```
Comment (tillmo) [inline backend/lqserver/lqserver/settings.py:113]: why have you thrown out these validators? Note that I have complained that pressing after "sign up", nothing happens. I strongly suspect that this was due to a password validation error. The problem was that the error was not shown, and I could not know how to correct my passwords. Hence, the solution would be to show the errors, not to omit the password validation.

Comment (tillmo) [reply backend/lqserver/lqserver/settings.py:113]: Aha, some general comment: there should be a django library for password validation etc. This library should be able to generate error messages. Then, this need not be done in the frontend.

Comment (MGlauer) [reply backend/lqserver/lqserver/settings.py:113]: I read a bit about React, so please @pramodkumarbontha correct my if I am wrong, but I guess the issue is the interaction between django and react: 
Django follows the Model-View-Controller approach and most Django applications rely on that. React on the other hand expects a strict separation onto backend and frontend whereas the frontend fetches the data from the backend via an API. These two concepts do not align very well.

Now towards the actual issue: Password validation (i.e. the check whether a password conforms to certain standards) is often done on the browser-side to lessen the server load and as far as I can see, the backend is using the auth functionality of `django-restframework`. So far, so good. But: These constraints *must* be enforced by the backend - checks on the client side are just "support". The backend has an API as described above - the idea is that this backend can be used by other applications, too. If the password policies are not enforced on the server side, it may happen that other applications can set passwords that are not usable within the frontend. Therefore: Validation of any kind *must* be done in the backend and *can* additionally enforced in the frontend.

Therefore, I would also recommend to reintroduce these basic validators in the backend and pass their error messages through the API.

Comment (pramodkumarbontha) [reply backend/lqserver/lqserver/settings.py:113]: @MGlauer Thank you for the insights. As you suggested I will implement the validators in the backend.

File: frontend/lqclient/src/components/Authentication/SignUp.jsx (hunk 1 above)
Comment (pramodkumarbontha) [reply frontend/lqclient/src/components/Authentication/SignUp.jsx:124]: @tillmo Could you please help me understand this. You meant about the validation or the string comparisons here?

Comment (tillmo) [reply frontend/lqclient/src/components/Authentication/SignUp.jsx:124]: I suggest to use a standard django library for validation. The frontend should just send the sign up data to the backend and display the error messages that have been sent by the backend (if any). In the frontend, validation (including such string comparisons and messages) should be completely omitted. This can be completely be delegated to the backend.

Comment (pramodkumarbontha) [reply frontend/lqclient/src/components/Authentication/SignUp.jsx]: @tillmo Committed the code for validations. Could you please review the changes once.
